### PR TITLE
[Bugfix] Error when retrieving locale object

### PR DESCRIPTION
**Pull request by Hanastaroth**
While readiing the intl.js file to check what I could use (or not) I found out that the `_getLocaleInstance` method used an unknown variable. 

I also added dependencies because while launching the test I encounter errors on the building phase.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by Hanastaroth** [comment]
CLA signed :)

**Comment by caridy** [comment]
@jasonmit don't we have linting configuration to catch these issues?

**Comment by jasonmit** [comment]
@Hanastaroth thanks for the PR.  Are you able to sign the CLA?  I'll write a test once it's merged to prevent a regression.

@caridy yes and `unused` is turned on.  I know ember-cli moved jshint out and into an addon, but I re-enabled it here https://github.com/yahoo/ember-intl/commit/63e0b7a4a4b01bdf6f6df6056f94a76dad2f5084

**Comment by jasonmit** [comment]
@Hanastaroth can you resubmit to pass the CLA check

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by jasonmit** [comment]
@Hanastaroth nevermind, all set :)

**Pull request merged**
