### PR TITLE
Update README to new addon install syntax

### PR DESCRIPTION
**Pull request by elwayman02**
Also, call out major browsers that will need the Intl shim

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by jasonmit** [comment]
Can you update it to support < 0.2.3 language as well since this command is relatively new

**Comment by elwayman02** [comment]
Yes

**Comment by elwayman02** [comment]
@jasonmit added

**Comment by jasonmit** [comment]
:+1:

**Pull request merged**
