### PR TITLE
Updating intl polyfill

### PR DESCRIPTION
**Pull request by jasonmit**

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by caridy** [comment]
+1, but tests are failing.

**Comment by jasonmit** [comment]
@caridy I pinged you offline to chat about what I believe might be related to https://github.com/andyearnshaw/Intl.js/issues/106

tests pass in Chrome fail in Phantom

**Comment by caridy** [comment]
@jasonmit according to our settings today (https://github.com/yahoo/intl-messageformat/blob/master/dist/intl-messageformat.js#L1646-L1670), we should be getting the `long` value after updating to 1.0.0-rc-1. We can probably test this in Safari and Phantom by doing: 

```
new Intl.DateTimeFormat( 'en', { month: 'long', day  : 'numeric', year : 'numeric' }).format(Date.now())
```

when I do that manually, in nodejs using the polyfill, I'm getting:

```
> new Intl.DateTimeFormat( 'en', { month: 'long', day  : 'numeric', year : 'numeric' }).format(Date.now())
'June 17, 2015'
> new IntlPolyfill.DateTimeFormat( 'en', { month: 'long', day  : 'numeric', year : 'numeric' }).format(Date.now())
'Jun 17, 2015'
```

**Comment by jasonmit** [comment]
Merged into the 2.0 branch

**Pull request closed without merging**
