### PR TITLE
Caching writer update

### PR DESCRIPTION
**Pull request by jasonmit**

### CODE REVIEW

**Comment by jasonmit** [comment]
@stefanpenner please review since I couldn't find docs on the new API

**Comment by stefanpenner** [comment]
sg

**Comment by jasonmit** [comment]
Ping @stefanpenner

**Comment by jasonmit** [comment]
I'll address anything you see, @stefanpenner but from the surface looks to be fine

**Comment by ryrych** [comment]
Hi,

I still have the problem.

```shell
ember build
Building
ember-intl: cannot read path "[...]/tmp/translation_preprocessor-input_base_path-658vg94b.tmp/0/en-us.yaml"
```

`package.json`
```json
"ember-intl": "2.0.0-rc.4"
```

`node_modules/ember-intl/package.json`
```
"name": "ember-intl",
"description": "Ember toolbox for internationalization.",
"version": "2.0.0-rc.4",
"directories": {
  "doc": "doc",
  "test": "tests"
}
```

`tests/index.html`
```html
{{content-for 'body'}}
{{content-for 'test-body'}}
<script src="assets/intl/intl.min.js"></script>
<script src="assets/intl/locales/en-us.js"></script>
<script src="assets/vendor.js"></script>
```

**Pull request merged**
